version: "3.9"
services:
    database:
        image: postgres
        restart: always
        hostname: localhost
        environment:
            POSTGRES_DB: "saved-pictures-holder"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "my-super-secret-password"
        ports:
            - "5432:5432"
        networks:
            - mynet

    server:
        depends_on:
            - database
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            DB_HOST: "database"
            DB_PORT: "5432"
            DB_NAME: "saved-pictures-holder"
            DB_USER: "postgres"
            DB_PASSWORD: "my-super-secret-password"
            PICTURE_PATH: "/data"
        ports:
            - "3000:3000"
        networks:
            - mynet


volumes:
    data:

networks:
    mynet:
        driver: bridge
        name: my-shared-db-network
